import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { SSR_CSS } from "../src/hiding-css.js";

const HEADER = `/**
 * phantom-ui SSR pre-hydration styles
 *
 * GENERATED by scripts/generate-ssr-css.ts from SSR_CSS in src/hiding-css.ts.
 * Do not edit by hand; run \`bun run build:ssr\` instead.
 *
 * Import this file in your SSR layout/entry file to prevent content flash
 * before the Web Component hydrates:
 *
 *   import "@aejkatappaja/phantom-ui/ssr.css";
 *
 * These rules mirror the styles phantom-ui adopts at runtime, so content inside
 * <phantom-ui loading> is hidden even before JavaScript executes.
 */
`;

// Written unformatted: `build:ssr` runs biome over the result, which is already the
// project's CSS formatter.
const out = fileURLToPath(new URL("../src/ssr.css", import.meta.url));
writeFileSync(out, `${HEADER}\n${SSR_CSS.trim()}\n`);
console.log(`wrote ${out}`);
